# Generated by Django 5.1.3 on 2025-07-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название группы (например, A-1, Python Kids и т.д.)', max_length=100, unique=True, verbose_name='Название группы')),
                ('telegram_id', models.CharField(blank=True, help_text='Введите Telegram ID группы, если есть (для отправки сообщений)', max_length=100, null=True, unique=True, verbose_name='Telegram ID группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
    ]
