# Generated by Django 5.1.3 on 2025-07-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Введите имя и фамилию ученика', max_length=100, verbose_name='Имя ученика')),
                ('task_title', models.CharField(help_text='Введите заголовок задания', max_length=100, verbose_name='Название задания')),
                ('task_condition', models.TextField(help_text='Введите условие задания', verbose_name='Условие')),
                ('student_answer', models.TextField(help_text='Введите ответ, который дал ученик', verbose_name='Ответ ученика')),
                ('grade', models.FloatField(blank=True, help_text='Оценка, выставленная за задание', null=True, verbose_name='Оценка (из 10)')),
                ('ai_feedback', models.TextField(blank=True, help_text='Отзыв или комментарий, сгенерированный cистемой Islam AI Checker', null=True, verbose_name='Комментарий от Islam AI Checker')),
                ('originality_check', models.TextField(blank=True, help_text='Проверка, сам ли ученик выполнил задание или использовал AI (например, ChatGPT)', null=True, verbose_name='Анализ оригинальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(help_text='Выберите группу, к которой относится задание', on_delete=django.db.models.deletion.CASCADE, related_name='homework_results', to='group.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Результат задания',
                'verbose_name_plural': 'Результаты заданий',
            },
        ),
    ]
